### ISSUE TITLE
Wrong manifest file for steam

### ISSUE THREAD

**Issue by hzfsls** [okibcn/ScoopMaster#6]
I have switched sources for all my apps to ScoopMaster and update them by "scoop update *". Then I found the version of steam was changed from nightly(from version bucket) to v018.1526499729, and then a hash check failed was reported.
I find the manifest file this bucket adopted was from [here](https://github.com/CometDog/scoop-bucket), which has stopped updating for 5 years.

**Comment by hzfsls** [comment]
<img width="640" alt="steam recognize" src="https://user-images.githubusercontent.com/52692664/221230237-5b60cd62-885f-4c8e-864d-c584d7662920.png">
The latest version of steam was mistakenly identified.

**Comment by okibcn** [comment]
Yes, there are a lot of extremely old manifests in the network and I need to improve the last revision algorithm or integrate some kind of blacklist for abandoned buckets interfering with the actual latest version.

While the second is easier to implement, a better algorithm would help more people.

In the meantime, you can temporarily install the Versions official bucket and assign steam to that bucket. All you have to do is to type this:
```pwsh
scoop bucket add Versions https://github.com/ScoopInstaller/Versions
(gc ~/scoop/apps/steam/current/install.json) -Replace '(?<=bucket":\s+")[^"]+','Versions' | Set-Content ~/scoop/apps/steam/current/install.json
```

Sorry for the inconvenience. It will be fixed in the next release.

**Comment by okibcn** [comment]
@hzfsls the new algorithm now filters out outdated manifests. Steam should now work along with other apps that were incorrectly using outdated manifests.

If you find more issues, please let me know. We can reopen this issue at any time.
